version: "3.8"
services:
    redis:
        image: redis:latest
        container_name: 'redis'
        ports:
            - 8888:6379
        networks:
            - default
    
    postgres:
        image: postgres:alpine
        container_name: 'postgres'
        ports:
            - 9999:5432
        volumes:
            - ./database/postgres:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: 1q2w3e4r5t6y
        networks:
            - default

networks:
    default:
        driver: bridge